motor1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 4
  Velocity_Limit: 65
  #Torque_Enable: 1
motor2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 4
  #Torque_Enable: 1
  Velocity_Limit: 65
motor3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 4
  #Torque_Enable: 1
  Velocity_Limit: 65
motor4:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 4
  #Torque_Enable: 1
  Velocity_Limit: 65

