motor1:
  ID: 1
  #Torque_Enable: 1
  Return_Delay_Time: 0
  Operating_Mode: 4
  Velocity_Limit: 131
motor2:
  ID: 2
  #Torque_Enable: 1
  Return_Delay_Time: 0
  Operating_Mode: 4
  Velocity_Limit: 131
motor3:
  ID: 3
  #Torque_Enable: 1
  Return_Delay_Time: 0
  Operating_Mode: 4
  Velocity_Limit: 131

